# # register account

POST https://cloud.appwrite.io/v1/account HTTP/1.1
Content-Type: application/json
X-Appwrite-Response-Format: 1.5.0
X-Appwrite-Project: X-Appwrite-Project

{
  "userId": "unique()",
  "email": "redapple@email.com",
  "password": "applesarered",
  "name": "redapple"
}

# # get current session for logout

GET https://cloud.appwrite.io/v1/account/sessions HTTP/1.1
Content-Type: application/json
X-Appwrite-Response-Format: 1.5.0
X-Appwrite-Project: X-Appwrite-Project

# # log-in account

POST https://cloud.appwrite.io/v1/account/sessions/email HTTP/1.1
Content-Type: application/json
X-Appwrite-Response-Format: 1.5.0
X-Appwrite-Project: X-Appwrite-Project

{
  "email": "redapple@email.com",
  "password": "applesarered"
}

# #logout account

DELETE https://cloud.appwrite.io/v1/account/sessions/{sessionID} HTTP/1.1
X-Appwrite-Response-Format: 1.5.0
X-Appwrite-Project: X-Appwrite-Project
X-Appwrite-Session: sessionID

